### ISSUE TITLE
关于EasyReport项目的基本问题

### ISSUE THREAD

**Issue by yuchaozhou** [xianrendzw/EasyReport#1]
首先感谢@xianrendzw 无私开源，谢谢！

1、项目下一阶段的Roadmap规划好否？

2、ReadMe文档最后两部分补充计划完成时间？

谢谢！

**Comment by xianrendzw** [comment]
1.项目计划与2016年元月份开始重构，主要是前端js交互与图表生成相关功能配置，还有部分java代码。
2.readme后面两部分准备在2016春节后可以完成

**Comment by woderia** [comment]
关注

**Comment by myd1** [comment]
focus on
