### ISSUE TITLE
小计和合计具体如何实现/思路

### ISSUE THREAD

**Issue by rockychen1221** [xianrendzw/EasyReport#68]
@xianrendzw  你好，我在`designer.js`中有发现小计和合计，但是后台没有发现任何与之相关的操作，我看到小计和合计处于注释状态，我想可能是因为没来得及开发，在此想请教下实现思路，自己也在尝试摸索中，谢谢

**Comment by rockychen1221** [comment]
<img width="1864" alt="total" src="https://user-images.githubusercontent.com/18478652/63907276-665a5780-ca4d-11e9-88fe-77ef55a41009.png">
初步完成

**Comment by farming789** [comment]
请问是怎么解决的呢？修改easyreport的代码吗？还是修改报表的配置？

**Comment by sindyX** [comment]
有现成的功能的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"farming789"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月4日(星期三) 下午4:11
收件人:&nbsp;"xianrendzw/EasyReport"<EasyReport@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [xianrendzw/EasyReport] 小计和合计具体如何实现/思路 (#68)




请问是怎么解决的呢？修改easyreport的代码吗？还是修改报表的配置？

**Comment by shimmer-one** [comment]
> <img alt="total" width="1864" src="https://user-images.githubusercontent.com/18478652/63907276-665a5780-ca4d-11e9-88fe-77ef55a41009.png">
> 初步完成

咨询下怎么处理的。加2列计算列吗，一列小计，一列合计？这表达式怎么填写啊
