### ISSUE TITLE
hi  报表引擎接口(Reporting Engine API)  在那查看？

### ISSUE THREAD

**Issue by zengbotang** [xianrendzw/EasyReport#7]
hi  报表引擎接口(Reporting Engine API)  在那查看？

**Comment by bjxiaowen** [comment]
我也不清楚，我也是引用的别人的。


原始邮件
发件人:zengbotangnotifications@github.com
收件人:xianrendzw/EasyReportEasyReport@noreply.github.com
发送时间:2016年11月22日(周二) 17:39
主题:[xianrendzw/EasyReport] hi 报表引擎接口(Reporting Engine API) 在那查看？ (#7)


hi 报表引擎接口(Reporting Engine API) 在那查看？

**Comment by zengbotang** [comment]
@bjxiaowen  源项目在那？给个链接吧，谢谢

**Comment by bjxiaowen** [comment]
我在github上帮你找找


原始邮件
发件人:zengbotangnotifications@github.com
收件人:xianrendzw/EasyReportEasyReport@noreply.github.com
抄送:bjxiaowenbjxiaowen@126.com; Mentionmention@noreply.github.com
发送时间:2016年11月22日(周二) 17:47
主题:Re: [xianrendzw/EasyReport] hi 报表引擎接口(Reporting Engine API) 在那查看？ (#7)


@bjxiaowen 源项目在那？给个链接吧，谢谢

**Comment by xianrendzw** [comment]
这块还没有整理出来，2.1版之后会整理

**Comment by WEIQ311** [comment]
2.1版什么时间更新呢？

**Comment by Jeadren** [comment]
@xianrendzw 现在2.1出来了，REST API怎么用？

**Comment by andyhithub** [comment]
有REST API简直太好了，还要摸索一下怎么用，http://localhost:9000/swagger-ui.html
