### ISSUE TITLE
支持大数据产品查询引擎(Hive,Presto,HBase,Drill,Impala等）  有详细文档吗？

### ISSUE THREAD

**Issue by zengbotang** [xianrendzw/EasyReport#9]
文档中又说支持大数据产品查询，但是没具体说，有具体的点的文档吗？

**Comment by xianrendzw** [comment]
这一块在Queryer 模块里，每个实现类上都有相应的集成链接。可以参考各产品的集成方案，自己实现试一试。

**Comment by WEIQ311** [comment]
我在engine模块中加hive依赖之后项目就启动不了，请问你是怎么做的hive支持的？`
`<dependency>`
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-hdfs</artifactId>
            <version>2.6.4</version>
        </dependency>
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-common</artifactId>
            <version>2.6.4</version>
        </dependency>
        <dependency>
            <groupId>org.apache.hive</groupId>
            <artifactId>hive-exec</artifactId>
            <version>2.1.0</version>
            <exclusions>
                <exclusion>
                    <artifactId>
                        pentaho-aggdesigner-algorithm
                    </artifactId>
                    <groupId>org.pentaho</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.hive</groupId>
            <artifactId>hive-jdbc</artifactId>
            <version>2.1.0</version>
        </dependency>`
